apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-app
      image: my-image:1.0
      readinessProbe:
        httpGet:
          path: /readiness
          port: 8080
      livenessProbe:
        httpGet:
          path: /liveness
          port: 8080



