apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: application
  labels:
    app: application
spec:
# TODO remove type
  type: LoadBalancer
  selector:
    app: application
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
